### PR TITLE
Add documentation for left drawer

### PR DESCRIPTION
**Pull request by emiglietta**
Check if this is enough and fits Erin's proposal

### CODE REVIEW

**Comment by bethac07** [comment]
If you've added a page, it needs to be added to the toc as well; please wait until we merge Erin's, which we can hopefuly do in a minute, then rebase yours on the current main, and then add this page to the correct section of the toc in her new organization. Thanks!

**Comment by bethac07** [comment]
@emiglietta Now you can rebase and add to toc, thanks!

**Comment by emiglietta** [comment]
I got kind of lost in git again, is this OK?

**Comment by bethac07** [comment]
Yup, looks great!

**Review by bethac07 — APPROVED** [review]

**Pull request merged**
